// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV4cntOPxjj5w0AAgT8-f6USw6MxA1GeQ',
    appId: '1:1095829998281:web:f050d8c79666f2b8b7db18',
    messagingSenderId: '1095829998281',
    projectId: 'kitahack-695c5',
    authDomain: 'kitahack-695c5.firebaseapp.com',
    storageBucket: 'kitahack-695c5.firebasestorage.app',
    measurementId: 'G-GWSG2YGZNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRXmFfpilrwXTtebpOzjiNmykIDcmmqyY',
    appId: '1:1095829998281:android:d2bb7a66040f65d3b7db18',
    messagingSenderId: '1095829998281',
    projectId: 'kitahack-695c5',
    storageBucket: 'kitahack-695c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdE4EkjNbyJTD-Sksuo_P1SBO4nwcCoto',
    appId: '1:1095829998281:ios:ff58edc4425a8d8eb7db18',
    messagingSenderId: '1095829998281',
    projectId: 'kitahack-695c5',
    storageBucket: 'kitahack-695c5.firebasestorage.app',
    iosBundleId: 'com.example.kitahackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdE4EkjNbyJTD-Sksuo_P1SBO4nwcCoto',
    appId: '1:1095829998281:ios:ff58edc4425a8d8eb7db18',
    messagingSenderId: '1095829998281',
    projectId: 'kitahack-695c5',
    storageBucket: 'kitahack-695c5.firebasestorage.app',
    iosBundleId: 'com.example.kitahackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV4cntOPxjj5w0AAgT8-f6USw6MxA1GeQ',
    appId: '1:1095829998281:web:1feafb969bea19efb7db18',
    messagingSenderId: '1095829998281',
    projectId: 'kitahack-695c5',
    authDomain: 'kitahack-695c5.firebaseapp.com',
    storageBucket: 'kitahack-695c5.firebasestorage.app',
    measurementId: 'G-XSM313282N',
  );
}
